packageExtensions:
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  react-responsive-masonry@*:
    dependencies:
      prop-types: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220325.hash-c66fcd9.cjs
